version: '3.8'

services:
  student-db:
    image: mysql:8.0
    container_name: student-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_db
    ports:
      - "3306:3306"
    networks:
      - microservice-network

  course-db:
    image: mysql:8.0
    container_name: course-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_db
    ports:
      - "3307:3306"
    networks:
      - microservice-network

  enrollment-db:
    image: mysql:8.0
    container_name: enrollment-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: enrollment_db
    ports:
      - "3308:3306"
    networks:
      - microservice-network

  result-db:
    image: mysql:8.0
    container_name: result-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: result_db
    ports:
      - "3309:3306"
    networks:
      - microservice-network

  notification-db:
    image: mysql:8.0
    container_name: notification-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_db
    ports:
      - "3310:3306"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
